services:
  edge:
    image: 'mezmohq/vector:3.1.2'
    environment:
      MEZMO_LOCAL_DEPLOY_AUTH_TOKEN: ${MEZMO_PIPELINE_SERVICE_TOKEN}
      MEZMO_API_URI: ${MEZMO_API_URI}
      MEZMO_EDGE_ID: ${EDGE_ID}
      MEZMO_METRICS_ENDPOINT_URL: ${MEZMO_API_URI}/metric/usage?edge_id=${EDGE_ID}
      MEZMO_TASKS_FETCH_ENDPOINT_URL: ${MEZMO_API_URI}/tasks?edge_id=${EDGE_ID}
      MEZMO_TASKS_POST_ENDPOINT_URL: ${MEZMO_API_URI}/tasks/:task_id/results
      MEZMO_RESHAPE_MESSAGE: 1
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/processor.yaml:/etc/vector/processor.yaml
      # change this to a host mount to test specific volumes for disk buffering
      - ${PWD}/tmp-data:/data/vector
    command: ["--config-dir", "/etc/vector"]
